//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interview1
{
    using System;
    using System.Collections.Generic;
    
    public partial class fg_bookslist
    {
        public int id { get; set; }
        public string name { get; set; }
        public string authors { get; set; }
        public string language { get; set; }
        public int booknumber { get; set; }
    }
}
